"""Public rollout construction, transition, and observation interfaces."""

from footballworld.dynamics.action import ACTION_TRACE_SCHEMA
from footballworld.environment.action_availability import (
    ACTION_INTENT_NAMES,
    intent_availability_hint,
)
from footballworld.environment.api import (
    ActingGoalkeeperEvent,
    FootballWorld,
    ManagementInitialization,
    ManagementRules,
    ManagerActingGoalkeeperCommand,
    ManagerAction,
    ManagerCommand,
    ManagerCommandReason,
    ManagerCommandStepResult,
    ManagerFormationCommand,
    ManagerObservation,
    ManagerSetPieceTakerCommand,
    ManagerState,
    ManagerStepResult,
    ManagerSubstitutionCommand,
    NormalizationContext,
    NormalizedBallState,
    NormalizedGlobalRollout,
    NormalizedGlobalState,
    NormalizedManagerObservation,
    NormalizedObservation,
    NormalizedPlayerTacticalObservation,
    NormalizedRosterMetadata,
    Observation,
    OpeningFormationStepResult,
    PlayerObservation,
    PlayerTacticalObservation,
    ResetResult,
    Rollout,
    RosterMetadata,
    SIManagerObservation,
    SIObservation,
    SIPlayerTacticalObservation,
    SIRollout,
    SIRosterMetadata,
    SquadSetup,
    StepResult,
    StepWithEventsResult,
    SubstitutionEvent,
    SubstitutionRequest,
    SubstitutionStepResult,
    emergency_goalkeeper_command,
)
from footballworld.environment.clock import MatchClockTicks, NormalizedMatchClock
from footballworld.environment.episode import MatchConfig, MatchSetup, RuleOutcome
from footballworld.environment.management import (
    MANAGER_OBSERVATION_SCHEMA_VERSION as SI_MANAGER_OBSERVATION_SCHEMA_VERSION,
)
from footballworld.environment.management import (
    PLAYER_TACTICAL_OBSERVATION_SCHEMA_VERSION as SI_PLAYER_TACTICAL_OBSERVATION_SCHEMA_VERSION,
)
from footballworld.environment.normalization import (
    MODEL_MANAGER_OBSERVATION_SCHEMA_VERSION,
    MODEL_OBSERVATION_SCHEMA_VERSION,
    MODEL_ROSTER_SCHEMA_VERSION,
    MODEL_STATE_SCHEMA_VERSION,
    MODEL_TACTICAL_OBSERVATION_SCHEMA_VERSION,
)
from footballworld.environment.observation import (
    PLAYER_OBSERVATION_SCHEMA_VERSION as SI_PLAYER_OBSERVATION_SCHEMA_VERSION,
)
from footballworld.environment.observation import (
    ROSTER_METADATA_SCHEMA_VERSION as SI_ROSTER_METADATA_SCHEMA_VERSION,
)
from footballworld.environment.transition import (
    ACTION_FLAG_NAMES,
    ACTION_REASON_NAMES,
    ACTION_RECEIPT_SCHEMA,
    DISPLACEMENT_SOURCE_NAMES,
    ELIGIBILITY_NAMES,
    PARAMETER_NAMES,
    ActionReceipt,
    ActionTrace,
    FrameEvents,
    NutmegEvent,
)

PLAYER_OBSERVATION_SCHEMA_VERSION = MODEL_OBSERVATION_SCHEMA_VERSION
ROSTER_METADATA_SCHEMA_VERSION = MODEL_ROSTER_SCHEMA_VERSION

__all__ = [
    "ACTION_FLAG_NAMES",
    "ACTION_INTENT_NAMES",
    "ACTION_REASON_NAMES",
    "ACTION_RECEIPT_SCHEMA",
    "ACTION_TRACE_SCHEMA",
    "DISPLACEMENT_SOURCE_NAMES",
    "ELIGIBILITY_NAMES",
    "MODEL_MANAGER_OBSERVATION_SCHEMA_VERSION",
    "MODEL_OBSERVATION_SCHEMA_VERSION",
    "MODEL_ROSTER_SCHEMA_VERSION",
    "MODEL_STATE_SCHEMA_VERSION",
    "MODEL_TACTICAL_OBSERVATION_SCHEMA_VERSION",
    "PARAMETER_NAMES",
    "PLAYER_OBSERVATION_SCHEMA_VERSION",
    "ROSTER_METADATA_SCHEMA_VERSION",
    "SI_MANAGER_OBSERVATION_SCHEMA_VERSION",
    "SI_PLAYER_OBSERVATION_SCHEMA_VERSION",
    "SI_PLAYER_TACTICAL_OBSERVATION_SCHEMA_VERSION",
    "SI_ROSTER_METADATA_SCHEMA_VERSION",
    "ActingGoalkeeperEvent",
    "ActionReceipt",
    "ActionTrace",
    "FootballWorld",
    "FrameEvents",
    "ManagementInitialization",
    "ManagementRules",
    "ManagerActingGoalkeeperCommand",
    "ManagerAction",
    "ManagerCommand",
    "ManagerCommandReason",
    "ManagerCommandStepResult",
    "ManagerFormationCommand",
    "ManagerObservation",
    "ManagerSetPieceTakerCommand",
    "ManagerState",
    "ManagerStepResult",
    "ManagerSubstitutionCommand",
    "MatchClockTicks",
    "MatchConfig",
    "MatchSetup",
    "NormalizationContext",
    "NormalizedBallState",
    "NormalizedGlobalRollout",
    "NormalizedGlobalState",
    "NormalizedManagerObservation",
    "NormalizedMatchClock",
    "NormalizedObservation",
    "NormalizedPlayerTacticalObservation",
    "NormalizedRosterMetadata",
    "NutmegEvent",
    "Observation",
    "OpeningFormationStepResult",
    "PlayerObservation",
    "PlayerTacticalObservation",
    "ResetResult",
    "Rollout",
    "RosterMetadata",
    "RuleOutcome",
    "SIManagerObservation",
    "SIObservation",
    "SIPlayerTacticalObservation",
    "SIRollout",
    "SIRosterMetadata",
    "SquadSetup",
    "StepResult",
    "StepWithEventsResult",
    "SubstitutionEvent",
    "SubstitutionRequest",
    "SubstitutionStepResult",
    "emergency_goalkeeper_command",
    "intent_availability_hint",
]
